// Code generated by "enumer --type=ComparatorType"; DO NOT EDIT.

package query

import (
	"fmt"
	"strings"
)

const _ComparatorTypeName = "CompareInvalidCompareDifferentCompareEqualCompareLessThanCompareLessThanEqualCompareGreaterThanCompareGreaterThanEqual"

var _ComparatorTypeIndex = [...]uint8{0, 14, 30, 42, 57, 77, 95, 118}

const _ComparatorTypeLowerName = "compareinvalidcomparedifferentcompareequalcomparelessthancomparelessthanequalcomparegreaterthancomparegreaterthanequal"

func (i ComparatorType) String() string {
	if i >= ComparatorType(len(_ComparatorTypeIndex)-1) {
		return fmt.Sprintf("ComparatorType(%d)", i)
	}
	return _ComparatorTypeName[_ComparatorTypeIndex[i]:_ComparatorTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ComparatorTypeNoOp() {
	var x [1]struct{}
	_ = x[CompareInvalid-(0)]
	_ = x[CompareDifferent-(1)]
	_ = x[CompareEqual-(2)]
	_ = x[CompareLessThan-(3)]
	_ = x[CompareLessThanEqual-(4)]
	_ = x[CompareGreaterThan-(5)]
	_ = x[CompareGreaterThanEqual-(6)]
}

var _ComparatorTypeValues = []ComparatorType{CompareInvalid, CompareDifferent, CompareEqual, CompareLessThan, CompareLessThanEqual, CompareGreaterThan, CompareGreaterThanEqual}

var _ComparatorTypeNameToValueMap = map[string]ComparatorType{
	_ComparatorTypeName[0:14]:        CompareInvalid,
	_ComparatorTypeLowerName[0:14]:   CompareInvalid,
	_ComparatorTypeName[14:30]:       CompareDifferent,
	_ComparatorTypeLowerName[14:30]:  CompareDifferent,
	_ComparatorTypeName[30:42]:       CompareEqual,
	_ComparatorTypeLowerName[30:42]:  CompareEqual,
	_ComparatorTypeName[42:57]:       CompareLessThan,
	_ComparatorTypeLowerName[42:57]:  CompareLessThan,
	_ComparatorTypeName[57:77]:       CompareLessThanEqual,
	_ComparatorTypeLowerName[57:77]:  CompareLessThanEqual,
	_ComparatorTypeName[77:95]:       CompareGreaterThan,
	_ComparatorTypeLowerName[77:95]:  CompareGreaterThan,
	_ComparatorTypeName[95:118]:      CompareGreaterThanEqual,
	_ComparatorTypeLowerName[95:118]: CompareGreaterThanEqual,
}

var _ComparatorTypeNames = []string{
	_ComparatorTypeName[0:14],
	_ComparatorTypeName[14:30],
	_ComparatorTypeName[30:42],
	_ComparatorTypeName[42:57],
	_ComparatorTypeName[57:77],
	_ComparatorTypeName[77:95],
	_ComparatorTypeName[95:118],
}

// ComparatorTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ComparatorTypeString(s string) (ComparatorType, error) {
	if val, ok := _ComparatorTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ComparatorTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ComparatorType values", s)
}

// ComparatorTypeValues returns all values of the enum
func ComparatorTypeValues() []ComparatorType {
	return _ComparatorTypeValues
}

// ComparatorTypeStrings returns a slice of all String values of the enum
func ComparatorTypeStrings() []string {
	strs := make([]string, len(_ComparatorTypeNames))
	copy(strs, _ComparatorTypeNames)
	return strs
}

// IsAComparatorType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ComparatorType) IsAComparatorType() bool {
	for _, v := range _ComparatorTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
