// Code generated by "enumer -type=PwnMethod -trimprefix=Pwn -json"; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PwnMethodName = "CreateUserCreateGroupCreateComputerCreateAnyObjectDeleteChildrenTargetDeleteObjectInheritsSecurityACLContainsDenyResetPasswordOwnsGenericAllWriteAllWritePropertyAllTakeOwnershipWriteDACLWriteSPNWriteValidatedSPNWriteAllowedToActAddMemberAddMemberGroupAttrAddSelfMemberReadMSAPasswordHasMSAWriteKeyCredentialLinkWriteAttributeSecurityGUIDSIDHistoryEqualityAllExtendedRightsDCReplicationGetChangesDCReplicationSyncronizeDSReplicationGetChangesAllReadLAPSPasswordMemberOfGroupHasSPNHasSPNNoPreauthAdminSDHolderOverwriteACLComputerAffectedByGPOGPOMachineConfigPartOfGPOGPOUserConfigPartOfGPOLocalAdminRightsLocalRDPRightsLocalDCOMRightsWriteAltSecurityIdentities"
const _PwnMethodLowerName = "createusercreategroupcreatecomputercreateanyobjectdeletechildrentargetdeleteobjectinheritssecurityaclcontainsdenyresetpasswordownsgenericallwriteallwritepropertyalltakeownershipwritedaclwritespnwritevalidatedspnwriteallowedtoactaddmemberaddmembergroupattraddselfmemberreadmsapasswordhasmsawritekeycredentiallinkwriteattributesecurityguidsidhistoryequalityallextendedrightsdcreplicationgetchangesdcreplicationsyncronizedsreplicationgetchangesallreadlapspasswordmemberofgrouphasspnhasspnnopreauthadminsdholderoverwriteaclcomputeraffectedbygpogpomachineconfigpartofgpogpouserconfigpartofgpolocaladminrightslocalrdprightslocaldcomrightswritealtsecurityidentities"

var _PwnMethodMap = map[PwnMethod]string{
	2:             _PwnMethodName[0:10],
	4:             _PwnMethodName[10:21],
	8:             _PwnMethodName[21:35],
	16:            _PwnMethodName[35:50],
	32:            _PwnMethodName[50:70],
	64:            _PwnMethodName[70:82],
	128:           _PwnMethodName[82:98],
	256:           _PwnMethodName[98:113],
	512:           _PwnMethodName[113:126],
	1024:          _PwnMethodName[126:130],
	2048:          _PwnMethodName[130:140],
	4096:          _PwnMethodName[140:148],
	8192:          _PwnMethodName[148:164],
	16384:         _PwnMethodName[164:177],
	32768:         _PwnMethodName[177:186],
	65536:         _PwnMethodName[186:194],
	131072:        _PwnMethodName[194:211],
	262144:        _PwnMethodName[211:228],
	524288:        _PwnMethodName[228:237],
	1048576:       _PwnMethodName[237:255],
	2097152:       _PwnMethodName[255:268],
	4194304:       _PwnMethodName[268:283],
	8388608:       _PwnMethodName[283:289],
	16777216:      _PwnMethodName[289:311],
	33554432:      _PwnMethodName[311:337],
	67108864:      _PwnMethodName[337:355],
	134217728:     _PwnMethodName[355:372],
	268435456:     _PwnMethodName[372:395],
	536870912:     _PwnMethodName[395:418],
	1073741824:    _PwnMethodName[418:444],
	2147483648:    _PwnMethodName[444:460],
	4294967296:    _PwnMethodName[460:473],
	8589934592:    _PwnMethodName[473:479],
	17179869184:   _PwnMethodName[479:494],
	34359738368:   _PwnMethodName[494:519],
	68719476736:   _PwnMethodName[519:540],
	137438953472:  _PwnMethodName[540:565],
	274877906944:  _PwnMethodName[565:587],
	549755813888:  _PwnMethodName[587:603],
	1099511627776: _PwnMethodName[603:617],
	2199023255552: _PwnMethodName[617:632],
	4398046511104: _PwnMethodName[632:658],
}

func (i PwnMethod) String() string {
	if str, ok := _PwnMethodMap[i]; ok {
		return str
	}
	return fmt.Sprintf("PwnMethod(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PwnMethodNoOp() {
	var x [1]struct{}
	_ = x[PwnCreateUser-(2)]
	_ = x[PwnCreateGroup-(4)]
	_ = x[PwnCreateComputer-(8)]
	_ = x[PwnCreateAnyObject-(16)]
	_ = x[PwnDeleteChildrenTarget-(32)]
	_ = x[PwnDeleteObject-(64)]
	_ = x[PwnInheritsSecurity-(128)]
	_ = x[PwnACLContainsDeny-(256)]
	_ = x[PwnResetPassword-(512)]
	_ = x[PwnOwns-(1024)]
	_ = x[PwnGenericAll-(2048)]
	_ = x[PwnWriteAll-(4096)]
	_ = x[PwnWritePropertyAll-(8192)]
	_ = x[PwnTakeOwnership-(16384)]
	_ = x[PwnWriteDACL-(32768)]
	_ = x[PwnWriteSPN-(65536)]
	_ = x[PwnWriteValidatedSPN-(131072)]
	_ = x[PwnWriteAllowedToAct-(262144)]
	_ = x[PwnAddMember-(524288)]
	_ = x[PwnAddMemberGroupAttr-(1048576)]
	_ = x[PwnAddSelfMember-(2097152)]
	_ = x[PwnReadMSAPassword-(4194304)]
	_ = x[PwnHasMSA-(8388608)]
	_ = x[PwnWriteKeyCredentialLink-(16777216)]
	_ = x[PwnWriteAttributeSecurityGUID-(33554432)]
	_ = x[PwnSIDHistoryEquality-(67108864)]
	_ = x[PwnAllExtendedRights-(134217728)]
	_ = x[PwnDCReplicationGetChanges-(268435456)]
	_ = x[PwnDCReplicationSyncronize-(536870912)]
	_ = x[PwnDSReplicationGetChangesAll-(1073741824)]
	_ = x[PwnReadLAPSPassword-(2147483648)]
	_ = x[PwnMemberOfGroup-(4294967296)]
	_ = x[PwnHasSPN-(8589934592)]
	_ = x[PwnHasSPNNoPreauth-(17179869184)]
	_ = x[PwnAdminSDHolderOverwriteACL-(34359738368)]
	_ = x[PwnComputerAffectedByGPO-(68719476736)]
	_ = x[PwnGPOMachineConfigPartOfGPO-(137438953472)]
	_ = x[PwnGPOUserConfigPartOfGPO-(274877906944)]
	_ = x[PwnLocalAdminRights-(549755813888)]
	_ = x[PwnLocalRDPRights-(1099511627776)]
	_ = x[PwnLocalDCOMRights-(2199023255552)]
	_ = x[PwnWriteAltSecurityIdentities-(4398046511104)]
}

var _PwnMethodValues = []PwnMethod{PwnCreateUser, PwnCreateGroup, PwnCreateComputer, PwnCreateAnyObject, PwnDeleteChildrenTarget, PwnDeleteObject, PwnInheritsSecurity, PwnACLContainsDeny, PwnResetPassword, PwnOwns, PwnGenericAll, PwnWriteAll, PwnWritePropertyAll, PwnTakeOwnership, PwnWriteDACL, PwnWriteSPN, PwnWriteValidatedSPN, PwnWriteAllowedToAct, PwnAddMember, PwnAddMemberGroupAttr, PwnAddSelfMember, PwnReadMSAPassword, PwnHasMSA, PwnWriteKeyCredentialLink, PwnWriteAttributeSecurityGUID, PwnSIDHistoryEquality, PwnAllExtendedRights, PwnDCReplicationGetChanges, PwnDCReplicationSyncronize, PwnDSReplicationGetChangesAll, PwnReadLAPSPassword, PwnMemberOfGroup, PwnHasSPN, PwnHasSPNNoPreauth, PwnAdminSDHolderOverwriteACL, PwnComputerAffectedByGPO, PwnGPOMachineConfigPartOfGPO, PwnGPOUserConfigPartOfGPO, PwnLocalAdminRights, PwnLocalRDPRights, PwnLocalDCOMRights, PwnWriteAltSecurityIdentities}

var _PwnMethodNameToValueMap = map[string]PwnMethod{
	_PwnMethodName[0:10]:         PwnCreateUser,
	_PwnMethodLowerName[0:10]:    PwnCreateUser,
	_PwnMethodName[10:21]:        PwnCreateGroup,
	_PwnMethodLowerName[10:21]:   PwnCreateGroup,
	_PwnMethodName[21:35]:        PwnCreateComputer,
	_PwnMethodLowerName[21:35]:   PwnCreateComputer,
	_PwnMethodName[35:50]:        PwnCreateAnyObject,
	_PwnMethodLowerName[35:50]:   PwnCreateAnyObject,
	_PwnMethodName[50:70]:        PwnDeleteChildrenTarget,
	_PwnMethodLowerName[50:70]:   PwnDeleteChildrenTarget,
	_PwnMethodName[70:82]:        PwnDeleteObject,
	_PwnMethodLowerName[70:82]:   PwnDeleteObject,
	_PwnMethodName[82:98]:        PwnInheritsSecurity,
	_PwnMethodLowerName[82:98]:   PwnInheritsSecurity,
	_PwnMethodName[98:113]:       PwnACLContainsDeny,
	_PwnMethodLowerName[98:113]:  PwnACLContainsDeny,
	_PwnMethodName[113:126]:      PwnResetPassword,
	_PwnMethodLowerName[113:126]: PwnResetPassword,
	_PwnMethodName[126:130]:      PwnOwns,
	_PwnMethodLowerName[126:130]: PwnOwns,
	_PwnMethodName[130:140]:      PwnGenericAll,
	_PwnMethodLowerName[130:140]: PwnGenericAll,
	_PwnMethodName[140:148]:      PwnWriteAll,
	_PwnMethodLowerName[140:148]: PwnWriteAll,
	_PwnMethodName[148:164]:      PwnWritePropertyAll,
	_PwnMethodLowerName[148:164]: PwnWritePropertyAll,
	_PwnMethodName[164:177]:      PwnTakeOwnership,
	_PwnMethodLowerName[164:177]: PwnTakeOwnership,
	_PwnMethodName[177:186]:      PwnWriteDACL,
	_PwnMethodLowerName[177:186]: PwnWriteDACL,
	_PwnMethodName[186:194]:      PwnWriteSPN,
	_PwnMethodLowerName[186:194]: PwnWriteSPN,
	_PwnMethodName[194:211]:      PwnWriteValidatedSPN,
	_PwnMethodLowerName[194:211]: PwnWriteValidatedSPN,
	_PwnMethodName[211:228]:      PwnWriteAllowedToAct,
	_PwnMethodLowerName[211:228]: PwnWriteAllowedToAct,
	_PwnMethodName[228:237]:      PwnAddMember,
	_PwnMethodLowerName[228:237]: PwnAddMember,
	_PwnMethodName[237:255]:      PwnAddMemberGroupAttr,
	_PwnMethodLowerName[237:255]: PwnAddMemberGroupAttr,
	_PwnMethodName[255:268]:      PwnAddSelfMember,
	_PwnMethodLowerName[255:268]: PwnAddSelfMember,
	_PwnMethodName[268:283]:      PwnReadMSAPassword,
	_PwnMethodLowerName[268:283]: PwnReadMSAPassword,
	_PwnMethodName[283:289]:      PwnHasMSA,
	_PwnMethodLowerName[283:289]: PwnHasMSA,
	_PwnMethodName[289:311]:      PwnWriteKeyCredentialLink,
	_PwnMethodLowerName[289:311]: PwnWriteKeyCredentialLink,
	_PwnMethodName[311:337]:      PwnWriteAttributeSecurityGUID,
	_PwnMethodLowerName[311:337]: PwnWriteAttributeSecurityGUID,
	_PwnMethodName[337:355]:      PwnSIDHistoryEquality,
	_PwnMethodLowerName[337:355]: PwnSIDHistoryEquality,
	_PwnMethodName[355:372]:      PwnAllExtendedRights,
	_PwnMethodLowerName[355:372]: PwnAllExtendedRights,
	_PwnMethodName[372:395]:      PwnDCReplicationGetChanges,
	_PwnMethodLowerName[372:395]: PwnDCReplicationGetChanges,
	_PwnMethodName[395:418]:      PwnDCReplicationSyncronize,
	_PwnMethodLowerName[395:418]: PwnDCReplicationSyncronize,
	_PwnMethodName[418:444]:      PwnDSReplicationGetChangesAll,
	_PwnMethodLowerName[418:444]: PwnDSReplicationGetChangesAll,
	_PwnMethodName[444:460]:      PwnReadLAPSPassword,
	_PwnMethodLowerName[444:460]: PwnReadLAPSPassword,
	_PwnMethodName[460:473]:      PwnMemberOfGroup,
	_PwnMethodLowerName[460:473]: PwnMemberOfGroup,
	_PwnMethodName[473:479]:      PwnHasSPN,
	_PwnMethodLowerName[473:479]: PwnHasSPN,
	_PwnMethodName[479:494]:      PwnHasSPNNoPreauth,
	_PwnMethodLowerName[479:494]: PwnHasSPNNoPreauth,
	_PwnMethodName[494:519]:      PwnAdminSDHolderOverwriteACL,
	_PwnMethodLowerName[494:519]: PwnAdminSDHolderOverwriteACL,
	_PwnMethodName[519:540]:      PwnComputerAffectedByGPO,
	_PwnMethodLowerName[519:540]: PwnComputerAffectedByGPO,
	_PwnMethodName[540:565]:      PwnGPOMachineConfigPartOfGPO,
	_PwnMethodLowerName[540:565]: PwnGPOMachineConfigPartOfGPO,
	_PwnMethodName[565:587]:      PwnGPOUserConfigPartOfGPO,
	_PwnMethodLowerName[565:587]: PwnGPOUserConfigPartOfGPO,
	_PwnMethodName[587:603]:      PwnLocalAdminRights,
	_PwnMethodLowerName[587:603]: PwnLocalAdminRights,
	_PwnMethodName[603:617]:      PwnLocalRDPRights,
	_PwnMethodLowerName[603:617]: PwnLocalRDPRights,
	_PwnMethodName[617:632]:      PwnLocalDCOMRights,
	_PwnMethodLowerName[617:632]: PwnLocalDCOMRights,
	_PwnMethodName[632:658]:      PwnWriteAltSecurityIdentities,
	_PwnMethodLowerName[632:658]: PwnWriteAltSecurityIdentities,
}

var _PwnMethodNames = []string{
	_PwnMethodName[0:10],
	_PwnMethodName[10:21],
	_PwnMethodName[21:35],
	_PwnMethodName[35:50],
	_PwnMethodName[50:70],
	_PwnMethodName[70:82],
	_PwnMethodName[82:98],
	_PwnMethodName[98:113],
	_PwnMethodName[113:126],
	_PwnMethodName[126:130],
	_PwnMethodName[130:140],
	_PwnMethodName[140:148],
	_PwnMethodName[148:164],
	_PwnMethodName[164:177],
	_PwnMethodName[177:186],
	_PwnMethodName[186:194],
	_PwnMethodName[194:211],
	_PwnMethodName[211:228],
	_PwnMethodName[228:237],
	_PwnMethodName[237:255],
	_PwnMethodName[255:268],
	_PwnMethodName[268:283],
	_PwnMethodName[283:289],
	_PwnMethodName[289:311],
	_PwnMethodName[311:337],
	_PwnMethodName[337:355],
	_PwnMethodName[355:372],
	_PwnMethodName[372:395],
	_PwnMethodName[395:418],
	_PwnMethodName[418:444],
	_PwnMethodName[444:460],
	_PwnMethodName[460:473],
	_PwnMethodName[473:479],
	_PwnMethodName[479:494],
	_PwnMethodName[494:519],
	_PwnMethodName[519:540],
	_PwnMethodName[540:565],
	_PwnMethodName[565:587],
	_PwnMethodName[587:603],
	_PwnMethodName[603:617],
	_PwnMethodName[617:632],
	_PwnMethodName[632:658],
}

// PwnMethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PwnMethodString(s string) (PwnMethod, error) {
	if val, ok := _PwnMethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PwnMethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PwnMethod values", s)
}

// PwnMethodValues returns all values of the enum
func PwnMethodValues() []PwnMethod {
	return _PwnMethodValues
}

// PwnMethodStrings returns a slice of all String values of the enum
func PwnMethodStrings() []string {
	strs := make([]string, len(_PwnMethodNames))
	copy(strs, _PwnMethodNames)
	return strs
}

// IsAPwnMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PwnMethod) IsAPwnMethod() bool {
	_, ok := _PwnMethodMap[i]
	return ok
}

// MarshalJSON implements the json.Marshaler interface for PwnMethod
func (i PwnMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PwnMethod
func (i *PwnMethod) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PwnMethod should be a string, got %s", data)
	}

	var err error
	*i, err = PwnMethodString(s)
	return err
}
