// Code generated by "enumer -type=ObjectType -trimprefix=ObjectType -json"; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ObjectTypeName = "OtherAttributeSchemaGroupForeignSecurityPrincipalDomainDNSUserComputerManagedServiceAccountOrganizationalUnitContainerGroupPolicyContainerCertificateTemplateTrustServiceExecutable"

var _ObjectTypeIndex = [...]uint8{0, 5, 20, 25, 49, 58, 62, 70, 91, 109, 118, 138, 157, 162, 169, 179}

const _ObjectTypeLowerName = "otherattributeschemagroupforeignsecurityprincipaldomaindnsusercomputermanagedserviceaccountorganizationalunitcontainergrouppolicycontainercertificatetemplatetrustserviceexecutable"

func (i ObjectType) String() string {
	i -= 1
	if i >= ObjectType(len(_ObjectTypeIndex)-1) {
		return fmt.Sprintf("ObjectType(%d)", i+1)
	}
	return _ObjectTypeName[_ObjectTypeIndex[i]:_ObjectTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ObjectTypeNoOp() {
	var x [1]struct{}
	_ = x[ObjectTypeOther-(1)]
	_ = x[ObjectTypeAttributeSchema-(2)]
	_ = x[ObjectTypeGroup-(3)]
	_ = x[ObjectTypeForeignSecurityPrincipal-(4)]
	_ = x[ObjectTypeDomainDNS-(5)]
	_ = x[ObjectTypeUser-(6)]
	_ = x[ObjectTypeComputer-(7)]
	_ = x[ObjectTypeManagedServiceAccount-(8)]
	_ = x[ObjectTypeOrganizationalUnit-(9)]
	_ = x[ObjectTypeContainer-(10)]
	_ = x[ObjectTypeGroupPolicyContainer-(11)]
	_ = x[ObjectTypeCertificateTemplate-(12)]
	_ = x[ObjectTypeTrust-(13)]
	_ = x[ObjectTypeService-(14)]
	_ = x[ObjectTypeExecutable-(15)]
}

var _ObjectTypeValues = []ObjectType{ObjectTypeOther, ObjectTypeAttributeSchema, ObjectTypeGroup, ObjectTypeForeignSecurityPrincipal, ObjectTypeDomainDNS, ObjectTypeUser, ObjectTypeComputer, ObjectTypeManagedServiceAccount, ObjectTypeOrganizationalUnit, ObjectTypeContainer, ObjectTypeGroupPolicyContainer, ObjectTypeCertificateTemplate, ObjectTypeTrust, ObjectTypeService, ObjectTypeExecutable}

var _ObjectTypeNameToValueMap = map[string]ObjectType{
	_ObjectTypeName[0:5]:          ObjectTypeOther,
	_ObjectTypeLowerName[0:5]:     ObjectTypeOther,
	_ObjectTypeName[5:20]:         ObjectTypeAttributeSchema,
	_ObjectTypeLowerName[5:20]:    ObjectTypeAttributeSchema,
	_ObjectTypeName[20:25]:        ObjectTypeGroup,
	_ObjectTypeLowerName[20:25]:   ObjectTypeGroup,
	_ObjectTypeName[25:49]:        ObjectTypeForeignSecurityPrincipal,
	_ObjectTypeLowerName[25:49]:   ObjectTypeForeignSecurityPrincipal,
	_ObjectTypeName[49:58]:        ObjectTypeDomainDNS,
	_ObjectTypeLowerName[49:58]:   ObjectTypeDomainDNS,
	_ObjectTypeName[58:62]:        ObjectTypeUser,
	_ObjectTypeLowerName[58:62]:   ObjectTypeUser,
	_ObjectTypeName[62:70]:        ObjectTypeComputer,
	_ObjectTypeLowerName[62:70]:   ObjectTypeComputer,
	_ObjectTypeName[70:91]:        ObjectTypeManagedServiceAccount,
	_ObjectTypeLowerName[70:91]:   ObjectTypeManagedServiceAccount,
	_ObjectTypeName[91:109]:       ObjectTypeOrganizationalUnit,
	_ObjectTypeLowerName[91:109]:  ObjectTypeOrganizationalUnit,
	_ObjectTypeName[109:118]:      ObjectTypeContainer,
	_ObjectTypeLowerName[109:118]: ObjectTypeContainer,
	_ObjectTypeName[118:138]:      ObjectTypeGroupPolicyContainer,
	_ObjectTypeLowerName[118:138]: ObjectTypeGroupPolicyContainer,
	_ObjectTypeName[138:157]:      ObjectTypeCertificateTemplate,
	_ObjectTypeLowerName[138:157]: ObjectTypeCertificateTemplate,
	_ObjectTypeName[157:162]:      ObjectTypeTrust,
	_ObjectTypeLowerName[157:162]: ObjectTypeTrust,
	_ObjectTypeName[162:169]:      ObjectTypeService,
	_ObjectTypeLowerName[162:169]: ObjectTypeService,
	_ObjectTypeName[169:179]:      ObjectTypeExecutable,
	_ObjectTypeLowerName[169:179]: ObjectTypeExecutable,
}

var _ObjectTypeNames = []string{
	_ObjectTypeName[0:5],
	_ObjectTypeName[5:20],
	_ObjectTypeName[20:25],
	_ObjectTypeName[25:49],
	_ObjectTypeName[49:58],
	_ObjectTypeName[58:62],
	_ObjectTypeName[62:70],
	_ObjectTypeName[70:91],
	_ObjectTypeName[91:109],
	_ObjectTypeName[109:118],
	_ObjectTypeName[118:138],
	_ObjectTypeName[138:157],
	_ObjectTypeName[157:162],
	_ObjectTypeName[162:169],
	_ObjectTypeName[169:179],
}

// ObjectTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ObjectTypeString(s string) (ObjectType, error) {
	if val, ok := _ObjectTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ObjectTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ObjectType values", s)
}

// ObjectTypeValues returns all values of the enum
func ObjectTypeValues() []ObjectType {
	return _ObjectTypeValues
}

// ObjectTypeStrings returns a slice of all String values of the enum
func ObjectTypeStrings() []string {
	strs := make([]string, len(_ObjectTypeNames))
	copy(strs, _ObjectTypeNames)
	return strs
}

// IsAObjectType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ObjectType) IsAObjectType() bool {
	for _, v := range _ObjectTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ObjectType
func (i ObjectType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ObjectType
func (i *ObjectType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ObjectType should be a string, got %s", data)
	}

	var err error
	*i, err = ObjectTypeString(s)
	return err
}
