// Code generated by "enumer -type=PwnMethod -trimprefix=Pwn -json"; DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PwnMethodName = "CreateUserCreateGroupCreateComputerCreateAnyObjectDeleteChildrenTargetDeleteObjectInheritsSecurityACLContainsDenyResetPasswordOwnsGenericAllWriteAllWritePropertyAllWriteExtendedAllTakeOwnershipWriteDACLWriteSPNWriteValidatedSPNWriteAllowedToActAddMemberAddMemberGroupAttrAddSelfMemberReadMSAPasswordHasMSAWriteKeyCredentialLinkWriteAttributeSecurityGUIDSIDHistoryEqualityAllExtendedRightsDSReplicationSyncronizeDSReplicationGetChangesDSReplicationGetChangesAllDSReplicationGetChangesInFilteredSetReadLAPSPasswordMemberOfGroupHasSPNHasSPNNoPreauthAdminSDHolderOverwriteACLComputerAffectedByGPOGPOMachineConfigPartOfGPOGPOUserConfigPartOfGPOLocalAdminRightsLocalRDPRightsLocalDCOMRightsLocalSMSAdminsLocalSessionLastDayLocalSessionLastWeekLocalSessionLastMonthHasServiceAccountCredentialsHasAutoAdminLogonCredentialsScheduledTaskOnUNCPathMachineScriptWriteAltSecurityIdentitiesWriteProfilePathWriteScriptPathCertificateEnrollRunsExecutableHostsRunsAsExecuted"

var _PwnMethodIndex = [...]uint16{0, 10, 21, 35, 50, 70, 82, 98, 113, 126, 130, 140, 148, 164, 180, 193, 202, 210, 227, 244, 253, 271, 284, 299, 305, 327, 353, 371, 388, 411, 434, 460, 496, 512, 525, 531, 546, 571, 592, 617, 639, 655, 669, 684, 698, 717, 737, 758, 786, 814, 836, 849, 875, 891, 906, 923, 937, 942, 948, 956}

const _PwnMethodLowerName = "createusercreategroupcreatecomputercreateanyobjectdeletechildrentargetdeleteobjectinheritssecurityaclcontainsdenyresetpasswordownsgenericallwriteallwritepropertyallwriteextendedalltakeownershipwritedaclwritespnwritevalidatedspnwriteallowedtoactaddmemberaddmembergroupattraddselfmemberreadmsapasswordhasmsawritekeycredentiallinkwriteattributesecurityguidsidhistoryequalityallextendedrightsdsreplicationsyncronizedsreplicationgetchangesdsreplicationgetchangesalldsreplicationgetchangesinfilteredsetreadlapspasswordmemberofgrouphasspnhasspnnopreauthadminsdholderoverwriteaclcomputeraffectedbygpogpomachineconfigpartofgpogpouserconfigpartofgpolocaladminrightslocalrdprightslocaldcomrightslocalsmsadminslocalsessionlastdaylocalsessionlastweeklocalsessionlastmonthhasserviceaccountcredentialshasautoadminlogoncredentialsscheduledtaskonuncpathmachinescriptwritealtsecurityidentitieswriteprofilepathwritescriptpathcertificateenrollrunsexecutablehostsrunsasexecuted"

func (i PwnMethod) String() string {
	i -= 1
	if i < 0 || i >= PwnMethod(len(_PwnMethodIndex)-1) {
		return fmt.Sprintf("PwnMethod(%d)", i+1)
	}
	return _PwnMethodName[_PwnMethodIndex[i]:_PwnMethodIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PwnMethodNoOp() {
	var x [1]struct{}
	_ = x[PwnCreateUser-(1)]
	_ = x[PwnCreateGroup-(2)]
	_ = x[PwnCreateComputer-(3)]
	_ = x[PwnCreateAnyObject-(4)]
	_ = x[PwnDeleteChildrenTarget-(5)]
	_ = x[PwnDeleteObject-(6)]
	_ = x[PwnInheritsSecurity-(7)]
	_ = x[PwnACLContainsDeny-(8)]
	_ = x[PwnResetPassword-(9)]
	_ = x[PwnOwns-(10)]
	_ = x[PwnGenericAll-(11)]
	_ = x[PwnWriteAll-(12)]
	_ = x[PwnWritePropertyAll-(13)]
	_ = x[PwnWriteExtendedAll-(14)]
	_ = x[PwnTakeOwnership-(15)]
	_ = x[PwnWriteDACL-(16)]
	_ = x[PwnWriteSPN-(17)]
	_ = x[PwnWriteValidatedSPN-(18)]
	_ = x[PwnWriteAllowedToAct-(19)]
	_ = x[PwnAddMember-(20)]
	_ = x[PwnAddMemberGroupAttr-(21)]
	_ = x[PwnAddSelfMember-(22)]
	_ = x[PwnReadMSAPassword-(23)]
	_ = x[PwnHasMSA-(24)]
	_ = x[PwnWriteKeyCredentialLink-(25)]
	_ = x[PwnWriteAttributeSecurityGUID-(26)]
	_ = x[PwnSIDHistoryEquality-(27)]
	_ = x[PwnAllExtendedRights-(28)]
	_ = x[PwnDSReplicationSyncronize-(29)]
	_ = x[PwnDSReplicationGetChanges-(30)]
	_ = x[PwnDSReplicationGetChangesAll-(31)]
	_ = x[PwnDSReplicationGetChangesInFilteredSet-(32)]
	_ = x[PwnReadLAPSPassword-(33)]
	_ = x[PwnMemberOfGroup-(34)]
	_ = x[PwnHasSPN-(35)]
	_ = x[PwnHasSPNNoPreauth-(36)]
	_ = x[PwnAdminSDHolderOverwriteACL-(37)]
	_ = x[PwnComputerAffectedByGPO-(38)]
	_ = x[PwnGPOMachineConfigPartOfGPO-(39)]
	_ = x[PwnGPOUserConfigPartOfGPO-(40)]
	_ = x[PwnLocalAdminRights-(41)]
	_ = x[PwnLocalRDPRights-(42)]
	_ = x[PwnLocalDCOMRights-(43)]
	_ = x[PwnLocalSMSAdmins-(44)]
	_ = x[PwnLocalSessionLastDay-(45)]
	_ = x[PwnLocalSessionLastWeek-(46)]
	_ = x[PwnLocalSessionLastMonth-(47)]
	_ = x[PwnHasServiceAccountCredentials-(48)]
	_ = x[PwnHasAutoAdminLogonCredentials-(49)]
	_ = x[PwnScheduledTaskOnUNCPath-(50)]
	_ = x[PwnMachineScript-(51)]
	_ = x[PwnWriteAltSecurityIdentities-(52)]
	_ = x[PwnWriteProfilePath-(53)]
	_ = x[PwnWriteScriptPath-(54)]
	_ = x[PwnCertificateEnroll-(55)]
	_ = x[PwnRunsExecutable-(56)]
	_ = x[PwnHosts-(57)]
	_ = x[PwnRunsAs-(58)]
	_ = x[PwnExecuted-(59)]
}

var _PwnMethodValues = []PwnMethod{PwnCreateUser, PwnCreateGroup, PwnCreateComputer, PwnCreateAnyObject, PwnDeleteChildrenTarget, PwnDeleteObject, PwnInheritsSecurity, PwnACLContainsDeny, PwnResetPassword, PwnOwns, PwnGenericAll, PwnWriteAll, PwnWritePropertyAll, PwnWriteExtendedAll, PwnTakeOwnership, PwnWriteDACL, PwnWriteSPN, PwnWriteValidatedSPN, PwnWriteAllowedToAct, PwnAddMember, PwnAddMemberGroupAttr, PwnAddSelfMember, PwnReadMSAPassword, PwnHasMSA, PwnWriteKeyCredentialLink, PwnWriteAttributeSecurityGUID, PwnSIDHistoryEquality, PwnAllExtendedRights, PwnDSReplicationSyncronize, PwnDSReplicationGetChanges, PwnDSReplicationGetChangesAll, PwnDSReplicationGetChangesInFilteredSet, PwnReadLAPSPassword, PwnMemberOfGroup, PwnHasSPN, PwnHasSPNNoPreauth, PwnAdminSDHolderOverwriteACL, PwnComputerAffectedByGPO, PwnGPOMachineConfigPartOfGPO, PwnGPOUserConfigPartOfGPO, PwnLocalAdminRights, PwnLocalRDPRights, PwnLocalDCOMRights, PwnLocalSMSAdmins, PwnLocalSessionLastDay, PwnLocalSessionLastWeek, PwnLocalSessionLastMonth, PwnHasServiceAccountCredentials, PwnHasAutoAdminLogonCredentials, PwnScheduledTaskOnUNCPath, PwnMachineScript, PwnWriteAltSecurityIdentities, PwnWriteProfilePath, PwnWriteScriptPath, PwnCertificateEnroll, PwnRunsExecutable, PwnHosts, PwnRunsAs, PwnExecuted}

var _PwnMethodNameToValueMap = map[string]PwnMethod{
	_PwnMethodName[0:10]:         PwnCreateUser,
	_PwnMethodLowerName[0:10]:    PwnCreateUser,
	_PwnMethodName[10:21]:        PwnCreateGroup,
	_PwnMethodLowerName[10:21]:   PwnCreateGroup,
	_PwnMethodName[21:35]:        PwnCreateComputer,
	_PwnMethodLowerName[21:35]:   PwnCreateComputer,
	_PwnMethodName[35:50]:        PwnCreateAnyObject,
	_PwnMethodLowerName[35:50]:   PwnCreateAnyObject,
	_PwnMethodName[50:70]:        PwnDeleteChildrenTarget,
	_PwnMethodLowerName[50:70]:   PwnDeleteChildrenTarget,
	_PwnMethodName[70:82]:        PwnDeleteObject,
	_PwnMethodLowerName[70:82]:   PwnDeleteObject,
	_PwnMethodName[82:98]:        PwnInheritsSecurity,
	_PwnMethodLowerName[82:98]:   PwnInheritsSecurity,
	_PwnMethodName[98:113]:       PwnACLContainsDeny,
	_PwnMethodLowerName[98:113]:  PwnACLContainsDeny,
	_PwnMethodName[113:126]:      PwnResetPassword,
	_PwnMethodLowerName[113:126]: PwnResetPassword,
	_PwnMethodName[126:130]:      PwnOwns,
	_PwnMethodLowerName[126:130]: PwnOwns,
	_PwnMethodName[130:140]:      PwnGenericAll,
	_PwnMethodLowerName[130:140]: PwnGenericAll,
	_PwnMethodName[140:148]:      PwnWriteAll,
	_PwnMethodLowerName[140:148]: PwnWriteAll,
	_PwnMethodName[148:164]:      PwnWritePropertyAll,
	_PwnMethodLowerName[148:164]: PwnWritePropertyAll,
	_PwnMethodName[164:180]:      PwnWriteExtendedAll,
	_PwnMethodLowerName[164:180]: PwnWriteExtendedAll,
	_PwnMethodName[180:193]:      PwnTakeOwnership,
	_PwnMethodLowerName[180:193]: PwnTakeOwnership,
	_PwnMethodName[193:202]:      PwnWriteDACL,
	_PwnMethodLowerName[193:202]: PwnWriteDACL,
	_PwnMethodName[202:210]:      PwnWriteSPN,
	_PwnMethodLowerName[202:210]: PwnWriteSPN,
	_PwnMethodName[210:227]:      PwnWriteValidatedSPN,
	_PwnMethodLowerName[210:227]: PwnWriteValidatedSPN,
	_PwnMethodName[227:244]:      PwnWriteAllowedToAct,
	_PwnMethodLowerName[227:244]: PwnWriteAllowedToAct,
	_PwnMethodName[244:253]:      PwnAddMember,
	_PwnMethodLowerName[244:253]: PwnAddMember,
	_PwnMethodName[253:271]:      PwnAddMemberGroupAttr,
	_PwnMethodLowerName[253:271]: PwnAddMemberGroupAttr,
	_PwnMethodName[271:284]:      PwnAddSelfMember,
	_PwnMethodLowerName[271:284]: PwnAddSelfMember,
	_PwnMethodName[284:299]:      PwnReadMSAPassword,
	_PwnMethodLowerName[284:299]: PwnReadMSAPassword,
	_PwnMethodName[299:305]:      PwnHasMSA,
	_PwnMethodLowerName[299:305]: PwnHasMSA,
	_PwnMethodName[305:327]:      PwnWriteKeyCredentialLink,
	_PwnMethodLowerName[305:327]: PwnWriteKeyCredentialLink,
	_PwnMethodName[327:353]:      PwnWriteAttributeSecurityGUID,
	_PwnMethodLowerName[327:353]: PwnWriteAttributeSecurityGUID,
	_PwnMethodName[353:371]:      PwnSIDHistoryEquality,
	_PwnMethodLowerName[353:371]: PwnSIDHistoryEquality,
	_PwnMethodName[371:388]:      PwnAllExtendedRights,
	_PwnMethodLowerName[371:388]: PwnAllExtendedRights,
	_PwnMethodName[388:411]:      PwnDSReplicationSyncronize,
	_PwnMethodLowerName[388:411]: PwnDSReplicationSyncronize,
	_PwnMethodName[411:434]:      PwnDSReplicationGetChanges,
	_PwnMethodLowerName[411:434]: PwnDSReplicationGetChanges,
	_PwnMethodName[434:460]:      PwnDSReplicationGetChangesAll,
	_PwnMethodLowerName[434:460]: PwnDSReplicationGetChangesAll,
	_PwnMethodName[460:496]:      PwnDSReplicationGetChangesInFilteredSet,
	_PwnMethodLowerName[460:496]: PwnDSReplicationGetChangesInFilteredSet,
	_PwnMethodName[496:512]:      PwnReadLAPSPassword,
	_PwnMethodLowerName[496:512]: PwnReadLAPSPassword,
	_PwnMethodName[512:525]:      PwnMemberOfGroup,
	_PwnMethodLowerName[512:525]: PwnMemberOfGroup,
	_PwnMethodName[525:531]:      PwnHasSPN,
	_PwnMethodLowerName[525:531]: PwnHasSPN,
	_PwnMethodName[531:546]:      PwnHasSPNNoPreauth,
	_PwnMethodLowerName[531:546]: PwnHasSPNNoPreauth,
	_PwnMethodName[546:571]:      PwnAdminSDHolderOverwriteACL,
	_PwnMethodLowerName[546:571]: PwnAdminSDHolderOverwriteACL,
	_PwnMethodName[571:592]:      PwnComputerAffectedByGPO,
	_PwnMethodLowerName[571:592]: PwnComputerAffectedByGPO,
	_PwnMethodName[592:617]:      PwnGPOMachineConfigPartOfGPO,
	_PwnMethodLowerName[592:617]: PwnGPOMachineConfigPartOfGPO,
	_PwnMethodName[617:639]:      PwnGPOUserConfigPartOfGPO,
	_PwnMethodLowerName[617:639]: PwnGPOUserConfigPartOfGPO,
	_PwnMethodName[639:655]:      PwnLocalAdminRights,
	_PwnMethodLowerName[639:655]: PwnLocalAdminRights,
	_PwnMethodName[655:669]:      PwnLocalRDPRights,
	_PwnMethodLowerName[655:669]: PwnLocalRDPRights,
	_PwnMethodName[669:684]:      PwnLocalDCOMRights,
	_PwnMethodLowerName[669:684]: PwnLocalDCOMRights,
	_PwnMethodName[684:698]:      PwnLocalSMSAdmins,
	_PwnMethodLowerName[684:698]: PwnLocalSMSAdmins,
	_PwnMethodName[698:717]:      PwnLocalSessionLastDay,
	_PwnMethodLowerName[698:717]: PwnLocalSessionLastDay,
	_PwnMethodName[717:737]:      PwnLocalSessionLastWeek,
	_PwnMethodLowerName[717:737]: PwnLocalSessionLastWeek,
	_PwnMethodName[737:758]:      PwnLocalSessionLastMonth,
	_PwnMethodLowerName[737:758]: PwnLocalSessionLastMonth,
	_PwnMethodName[758:786]:      PwnHasServiceAccountCredentials,
	_PwnMethodLowerName[758:786]: PwnHasServiceAccountCredentials,
	_PwnMethodName[786:814]:      PwnHasAutoAdminLogonCredentials,
	_PwnMethodLowerName[786:814]: PwnHasAutoAdminLogonCredentials,
	_PwnMethodName[814:836]:      PwnScheduledTaskOnUNCPath,
	_PwnMethodLowerName[814:836]: PwnScheduledTaskOnUNCPath,
	_PwnMethodName[836:849]:      PwnMachineScript,
	_PwnMethodLowerName[836:849]: PwnMachineScript,
	_PwnMethodName[849:875]:      PwnWriteAltSecurityIdentities,
	_PwnMethodLowerName[849:875]: PwnWriteAltSecurityIdentities,
	_PwnMethodName[875:891]:      PwnWriteProfilePath,
	_PwnMethodLowerName[875:891]: PwnWriteProfilePath,
	_PwnMethodName[891:906]:      PwnWriteScriptPath,
	_PwnMethodLowerName[891:906]: PwnWriteScriptPath,
	_PwnMethodName[906:923]:      PwnCertificateEnroll,
	_PwnMethodLowerName[906:923]: PwnCertificateEnroll,
	_PwnMethodName[923:937]:      PwnRunsExecutable,
	_PwnMethodLowerName[923:937]: PwnRunsExecutable,
	_PwnMethodName[937:942]:      PwnHosts,
	_PwnMethodLowerName[937:942]: PwnHosts,
	_PwnMethodName[942:948]:      PwnRunsAs,
	_PwnMethodLowerName[942:948]: PwnRunsAs,
	_PwnMethodName[948:956]:      PwnExecuted,
	_PwnMethodLowerName[948:956]: PwnExecuted,
}

var _PwnMethodNames = []string{
	_PwnMethodName[0:10],
	_PwnMethodName[10:21],
	_PwnMethodName[21:35],
	_PwnMethodName[35:50],
	_PwnMethodName[50:70],
	_PwnMethodName[70:82],
	_PwnMethodName[82:98],
	_PwnMethodName[98:113],
	_PwnMethodName[113:126],
	_PwnMethodName[126:130],
	_PwnMethodName[130:140],
	_PwnMethodName[140:148],
	_PwnMethodName[148:164],
	_PwnMethodName[164:180],
	_PwnMethodName[180:193],
	_PwnMethodName[193:202],
	_PwnMethodName[202:210],
	_PwnMethodName[210:227],
	_PwnMethodName[227:244],
	_PwnMethodName[244:253],
	_PwnMethodName[253:271],
	_PwnMethodName[271:284],
	_PwnMethodName[284:299],
	_PwnMethodName[299:305],
	_PwnMethodName[305:327],
	_PwnMethodName[327:353],
	_PwnMethodName[353:371],
	_PwnMethodName[371:388],
	_PwnMethodName[388:411],
	_PwnMethodName[411:434],
	_PwnMethodName[434:460],
	_PwnMethodName[460:496],
	_PwnMethodName[496:512],
	_PwnMethodName[512:525],
	_PwnMethodName[525:531],
	_PwnMethodName[531:546],
	_PwnMethodName[546:571],
	_PwnMethodName[571:592],
	_PwnMethodName[592:617],
	_PwnMethodName[617:639],
	_PwnMethodName[639:655],
	_PwnMethodName[655:669],
	_PwnMethodName[669:684],
	_PwnMethodName[684:698],
	_PwnMethodName[698:717],
	_PwnMethodName[717:737],
	_PwnMethodName[737:758],
	_PwnMethodName[758:786],
	_PwnMethodName[786:814],
	_PwnMethodName[814:836],
	_PwnMethodName[836:849],
	_PwnMethodName[849:875],
	_PwnMethodName[875:891],
	_PwnMethodName[891:906],
	_PwnMethodName[906:923],
	_PwnMethodName[923:937],
	_PwnMethodName[937:942],
	_PwnMethodName[942:948],
	_PwnMethodName[948:956],
}

// PwnMethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PwnMethodString(s string) (PwnMethod, error) {
	if val, ok := _PwnMethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PwnMethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PwnMethod values", s)
}

// PwnMethodValues returns all values of the enum
func PwnMethodValues() []PwnMethod {
	return _PwnMethodValues
}

// PwnMethodStrings returns a slice of all String values of the enum
func PwnMethodStrings() []string {
	strs := make([]string, len(_PwnMethodNames))
	copy(strs, _PwnMethodNames)
	return strs
}

// IsAPwnMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PwnMethod) IsAPwnMethod() bool {
	for _, v := range _PwnMethodValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PwnMethod
func (i PwnMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PwnMethod
func (i *PwnMethod) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PwnMethod should be a string, got %s", data)
	}

	var err error
	*i, err = PwnMethodString(s)
	return err
}
