// Code generated by "enumer -type=WebServiceStatus -output enums.go"; DO NOT EDIT.

package frontend

import (
	"fmt"
	"strings"
)

const _WebServiceStatusName = "NoDataErrorLoadingAnalyzingPostAnalyzingReady"

var _WebServiceStatusIndex = [...]uint8{0, 6, 11, 18, 27, 40, 45}

const _WebServiceStatusLowerName = "nodataerrorloadinganalyzingpostanalyzingready"

func (i WebServiceStatus) String() string {
	if i < 0 || i >= WebServiceStatus(len(_WebServiceStatusIndex)-1) {
		return fmt.Sprintf("WebServiceStatus(%d)", i)
	}
	return _WebServiceStatusName[_WebServiceStatusIndex[i]:_WebServiceStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _WebServiceStatusNoOp() {
	var x [1]struct{}
	_ = x[NoData-(0)]
	_ = x[Error-(1)]
	_ = x[Loading-(2)]
	_ = x[Analyzing-(3)]
	_ = x[PostAnalyzing-(4)]
	_ = x[Ready-(5)]
}

var _WebServiceStatusValues = []WebServiceStatus{NoData, Error, Loading, Analyzing, PostAnalyzing, Ready}

var _WebServiceStatusNameToValueMap = map[string]WebServiceStatus{
	_WebServiceStatusName[0:6]:        NoData,
	_WebServiceStatusLowerName[0:6]:   NoData,
	_WebServiceStatusName[6:11]:       Error,
	_WebServiceStatusLowerName[6:11]:  Error,
	_WebServiceStatusName[11:18]:      Loading,
	_WebServiceStatusLowerName[11:18]: Loading,
	_WebServiceStatusName[18:27]:      Analyzing,
	_WebServiceStatusLowerName[18:27]: Analyzing,
	_WebServiceStatusName[27:40]:      PostAnalyzing,
	_WebServiceStatusLowerName[27:40]: PostAnalyzing,
	_WebServiceStatusName[40:45]:      Ready,
	_WebServiceStatusLowerName[40:45]: Ready,
}

var _WebServiceStatusNames = []string{
	_WebServiceStatusName[0:6],
	_WebServiceStatusName[6:11],
	_WebServiceStatusName[11:18],
	_WebServiceStatusName[18:27],
	_WebServiceStatusName[27:40],
	_WebServiceStatusName[40:45],
}

// WebServiceStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func WebServiceStatusString(s string) (WebServiceStatus, error) {
	if val, ok := _WebServiceStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _WebServiceStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to WebServiceStatus values", s)
}

// WebServiceStatusValues returns all values of the enum
func WebServiceStatusValues() []WebServiceStatus {
	return _WebServiceStatusValues
}

// WebServiceStatusStrings returns a slice of all String values of the enum
func WebServiceStatusStrings() []string {
	strs := make([]string, len(_WebServiceStatusNames))
	copy(strs, _WebServiceStatusNames)
	return strs
}

// IsAWebServiceStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i WebServiceStatus) IsAWebServiceStatus() bool {
	for _, v := range _WebServiceStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
