// Code generated by "enumer -type=TLSmode -json"; DO NOT EDIT.

//
package collect

import (
	"encoding/json"
	"fmt"
)

const _TLSmodeName = "TLSStartTLSNoTLS"

var _TLSmodeIndex = [...]uint8{0, 3, 11, 16}

func (i TLSmode) String() string {
	if i >= TLSmode(len(_TLSmodeIndex)-1) {
		return fmt.Sprintf("TLSmode(%d)", i)
	}
	return _TLSmodeName[_TLSmodeIndex[i]:_TLSmodeIndex[i+1]]
}

var _TLSmodeValues = []TLSmode{0, 1, 2}

var _TLSmodeNameToValueMap = map[string]TLSmode{
	_TLSmodeName[0:3]:   0,
	_TLSmodeName[3:11]:  1,
	_TLSmodeName[11:16]: 2,
}

// TLSmodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TLSmodeString(s string) (TLSmode, error) {
	if val, ok := _TLSmodeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TLSmode values", s)
}

// TLSmodeValues returns all values of the enum
func TLSmodeValues() []TLSmode {
	return _TLSmodeValues
}

// IsATLSmode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TLSmode) IsATLSmode() bool {
	for _, v := range _TLSmodeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for TLSmode
func (i TLSmode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for TLSmode
func (i *TLSmode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("TLSmode should be a string, got %s", data)
	}

	var err error
	*i, err = TLSmodeString(s)
	return err
}
