// Code generated by "enumer -type=ProcessPriority -output enums.go"; DO NOT EDIT.

package engine

import (
	"fmt"
	"strings"
)

const _ProcessPriorityName = "BeforeMergeLowBeforeMergeBeforeMergeHighAfterMergeLowAfterMergeAfterMergeHighAfterMergeFinal"

var _ProcessPriorityIndex = [...]uint8{0, 14, 25, 40, 53, 63, 77, 92}

const _ProcessPriorityLowerName = "beforemergelowbeforemergebeforemergehighaftermergelowaftermergeaftermergehighaftermergefinal"

func (i ProcessPriority) String() string {
	if i < 0 || i >= ProcessPriority(len(_ProcessPriorityIndex)-1) {
		return fmt.Sprintf("ProcessPriority(%d)", i)
	}
	return _ProcessPriorityName[_ProcessPriorityIndex[i]:_ProcessPriorityIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProcessPriorityNoOp() {
	var x [1]struct{}
	_ = x[BeforeMergeLow-(0)]
	_ = x[BeforeMerge-(1)]
	_ = x[BeforeMergeHigh-(2)]
	_ = x[AfterMergeLow-(3)]
	_ = x[AfterMerge-(4)]
	_ = x[AfterMergeHigh-(5)]
	_ = x[AfterMergeFinal-(6)]
}

var _ProcessPriorityValues = []ProcessPriority{BeforeMergeLow, BeforeMerge, BeforeMergeHigh, AfterMergeLow, AfterMerge, AfterMergeHigh, AfterMergeFinal}

var _ProcessPriorityNameToValueMap = map[string]ProcessPriority{
	_ProcessPriorityName[0:14]:       BeforeMergeLow,
	_ProcessPriorityLowerName[0:14]:  BeforeMergeLow,
	_ProcessPriorityName[14:25]:      BeforeMerge,
	_ProcessPriorityLowerName[14:25]: BeforeMerge,
	_ProcessPriorityName[25:40]:      BeforeMergeHigh,
	_ProcessPriorityLowerName[25:40]: BeforeMergeHigh,
	_ProcessPriorityName[40:53]:      AfterMergeLow,
	_ProcessPriorityLowerName[40:53]: AfterMergeLow,
	_ProcessPriorityName[53:63]:      AfterMerge,
	_ProcessPriorityLowerName[53:63]: AfterMerge,
	_ProcessPriorityName[63:77]:      AfterMergeHigh,
	_ProcessPriorityLowerName[63:77]: AfterMergeHigh,
	_ProcessPriorityName[77:92]:      AfterMergeFinal,
	_ProcessPriorityLowerName[77:92]: AfterMergeFinal,
}

var _ProcessPriorityNames = []string{
	_ProcessPriorityName[0:14],
	_ProcessPriorityName[14:25],
	_ProcessPriorityName[25:40],
	_ProcessPriorityName[40:53],
	_ProcessPriorityName[53:63],
	_ProcessPriorityName[63:77],
	_ProcessPriorityName[77:92],
}

// ProcessPriorityString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProcessPriorityString(s string) (ProcessPriority, error) {
	if val, ok := _ProcessPriorityNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProcessPriorityNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProcessPriority values", s)
}

// ProcessPriorityValues returns all values of the enum
func ProcessPriorityValues() []ProcessPriority {
	return _ProcessPriorityValues
}

// ProcessPriorityStrings returns a slice of all String values of the enum
func ProcessPriorityStrings() []string {
	strs := make([]string, len(_ProcessPriorityNames))
	copy(strs, _ProcessPriorityNames)
	return strs
}

// IsAProcessPriority returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProcessPriority) IsAProcessPriority() bool {
	for _, v := range _ProcessPriorityValues {
		if i == v {
			return true
		}
	}
	return false
}
